### ISSUE TITLE
Formatting Mistakes in 'Discussions'

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#214]
A couple things are formatted incorrectly, since Jordan re-booted the site to get /wp-admin working again.

The button on the front page above the fold to 'discuss with X others' has the wrong formatting, and the formatting of the text editor within 'discussions' also changed. The 'reply' button within 'Discussions' is wrong too.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @jetlej : 

The "Ajax BootModal Login" plugin was DEACTIVATED all this while and activating the plugin has caused this issue. 

<b>If we want the PLUGIN ACTIVATED </b>then here is the solution : 

go to Settings->BootModal Login settings -> Highlighted option should be CHECKED : http://screencast.com/t/dGxV0B9H

<b>If we want the plugin to be DEACTIVATED</b>, then deactivating the plugin should resolve the issue.

Let me know if this helps. Thanks !

**Comment by lostboyevsky** [comment]
@jetlej can i go ahead and deactivate this plugin then? or will that cause other problems?

**Comment by JonBrooksX** [comment]
I've seen this problem with the buttons below author bios too.

**Comment by MSchirp** [comment]
@dpatil-gmcs @jetlej I went ahead and checked the option because I assumed the plug in was already activated for a reason after the big reset. This broke the whole site if you're logged in. I tried unchecking the option and it is still broken. I tried deactivating the plug in, but the site is till broken.

**Comment by jetlej** [comment]
We want that plugin activated. I enabled that option so this is now fixed.
